# Disable Jekyll completely for this static site
exclude:
  - README.md
  - LICENSE
  - .gitignore

# No plugins needed for static site
plugins: []

# No layouts needed
layouts: null

# No collections
collections: {}

# No pagination
paginate: null
paginate_path: null

# No theme
theme: null

# No markdown processing
markdown: null

# No syntax highlighting
highlighter: null

# No sass processing
sass:
  style: compressed

# No coffee script
coffeescript: null